# This formula is generated by scripts/render-homebrew-formula.sh in
# guferreira1/spec-harbor. Do not edit it by hand.
class Specharbor < Formula
  desc "Spec-driven workflow CLI for AI coding agents"
  homepage "https://github.com/guferreira1/spec-harbor"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/guferreira1/spec-harbor/releases/download/v0.2.0/specharbor_Darwin_arm64.tar.gz"
      sha256 "9591fcb08c26896686c9324c800a4ee7f8f47f1632be50a04526657fe6047b14"
    end
    on_intel do
      url "https://github.com/guferreira1/spec-harbor/releases/download/v0.2.0/specharbor_Darwin_x86_64.tar.gz"
      sha256 "207c5464a8db9febacd40961edb97f2b3de523854e3d7aa20b5003f772e90ef3"
    end
  end

  def install
    bin.install "specharbor"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/specharbor version")
  end
end
