# This formula is generated by scripts/render-homebrew-formula.sh in
# guferreira1/spec-harbor. Do not edit it by hand.
class Specharbor < Formula
  desc "Spec-driven workflow CLI for AI coding agents"
  homepage "https://github.com/guferreira1/spec-harbor"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/guferreira1/spec-harbor/releases/download/v0.3.0/specharbor_Darwin_arm64.tar.gz"
      sha256 "6fc5d438990ac310ef646caae1aa739abc45c831b3b75175b7aa4a0c2bf30764"
    end
    on_intel do
      url "https://github.com/guferreira1/spec-harbor/releases/download/v0.3.0/specharbor_Darwin_x86_64.tar.gz"
      sha256 "452f1216fa59464884d74fc16d9e8e4ecbf41b5f15098ba8d3d3c29940204986"
    end
  end

  def install
    bin.install "specharbor"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/specharbor version")
  end
end
